---
- name: Run OpenSCAP compliance scan
  hosts: all
  become: yes
  tasks:
    - name: Install OpenSCAP tools
      dnf:
        name:
          - openscap-scanner
          - scap-security-guide
        state: present

    - name: Run scan and generate report
      command: >
        oscap xccdf eval --profile xccdf_org.ssgproject.content_profile_cis
        --results /tmp/openscap-results.xml
        --report /tmp/openscap-report.html
        /usr/share/xml/scap/ssg/content/ssg-rhel9-ds.xml
      args:
        warn: false
